import Foundation
import SwiftData

/// Orchestrates AI analysis for bookmark items
actor AIContentProcessor {
    /// Shared instance
    static let shared = AIContentProcessor()

    /// Minimum content length to warrant AI processing
    private let minContentLength = 20

    private init() {}

    /// Analyze a bookmark item and return AI-generated metadata
    /// - Parameter item: The bookmark item to analyze
    /// - Returns: AI analysis response
    /// - Throws: AIAnalysisError on failure
    func analyzeItem(_ item: BookmarkItem) async throws -> AIAnalysisResponse {
        // Skip if not enough content
        guard hasEnoughContent(item) else {
            throw AIAnalysisError.invalidResponse
        }

        let request = AIAnalysisRequest(from: item)
        return try await ResurfaceAPIClient.shared.analyzeContent(request)
    }

    /// Apply AI response to a bookmark item
    /// Must be called on MainActor with a valid ModelContext
    @MainActor
    func applyAnalysis(
        _ response: AIAnalysisResponse,
        to item: BookmarkItem,
        in context: ModelContext
    ) {
        // Auto-categorization: if the user didn't manually pick a category,
        // try to match the AI suggestion to an existing category
        if item.wasAutoCategorized || item.category == nil {
            if let matched = findMatchingCategory(for: response.category, in: context) {
                item.category = matched
                item.wasAutoCategorized = true
            }
        }

        // Find or create tags
        for tagName in response.tags {
            let lowercasedName = tagName.lowercased()
            let tagDescriptor = FetchDescriptor<Tag>(
                predicate: #Predicate<Tag> { $0.name == lowercasedName }
            )

            if let existingTag = try? context.fetch(tagDescriptor).first {
                if !item.tags.contains(where: { $0.id == existingTag.id }) {
                    item.tags.append(existingTag)
                    existingTag.incrementUsage()
                }
            } else {
                let newTag = Tag(name: lowercasedName, isAutoGenerated: true)
                context.insert(newTag)
                item.tags.append(newTag)
            }
        }

        // Apply other fields
        item.keyInsights = response.keyInsights
        item.contentSubtype = response.contentSubtype
        item.aiConfidence = response.confidence

        // Apply AI-generated title if provided
        if let suggestedTitle = response.suggestedTitle, !suggestedTitle.isEmpty {
            item.aiGeneratedTitle = suggestedTitle
        }

        // Apply extracted fields if provided
        if let extractedFields = response.extractedFields, !extractedFields.isEmpty {
            item.extractedFields = extractedFields
        }
    }

    /// Find an existing category matching the AI suggestion (does NOT auto-create)
    @MainActor
    private func findMatchingCategory(for suggestedName: String, in context: ModelContext) -> Category? {
        let descriptor = FetchDescriptor<Category>(
            predicate: #Predicate<Category> { !$0.isArchived }
        )
        guard let categories = try? context.fetch(descriptor) else { return nil }

        let lowered = suggestedName.lowercased()

        // Exact name match
        if let exact = categories.first(where: { $0.name.lowercased() == lowered }) {
            return exact
        }

        // Template keyword match — map AI suggestion to a known template, then find that category
        if let template = CategoryTemplates.bestMatch(for: lowered),
           let match = categories.first(where: { $0.name.lowercased() == template.name.lowercased() }) {
            return match
        }

        return nil
    }

    /// Check if item has enough content to analyze
    private func hasEnoughContent(_ item: BookmarkItem) -> Bool {
        let titleLength = item.title.count
        let textLength = (item.rawText ?? "").count + (item.webContent?.extractedText ?? "").count

        return titleLength + textLength >= minContentLength
    }
}
