import Foundation
import SwiftData

/// Orchestrates AI analysis for bookmark items
actor AIContentProcessor {
    /// Shared instance
    static let shared = AIContentProcessor()

    /// Minimum content length to warrant AI processing
    private let minContentLength = 20

    private init() {}

    /// Analyze a bookmark item and return AI-generated metadata
    /// - Parameter item: The bookmark item to analyze
    /// - Returns: AI analysis response
    /// - Throws: AIAnalysisError on failure
    func analyzeItem(_ item: BookmarkItem) async throws -> AIAnalysisResponse {
        // Skip if not enough content
        guard hasEnoughContent(item) else {
            throw AIAnalysisError.invalidResponse
        }

        let request = AIAnalysisRequest(from: item)
        return try await ResurfaceAPIClient.shared.analyzeContent(request)
    }

    /// Apply AI response to a bookmark item
    /// Must be called on MainActor with a valid ModelContext
    /// Note: Category is NOT updated here - users select their own categories at share time
    @MainActor
    func applyAnalysis(
        _ response: AIAnalysisResponse,
        to item: BookmarkItem,
        in context: ModelContext
    ) {
        // NOTE: We no longer auto-assign categories from AI response
        // Users select their category when sharing content
        // The AI analyzes through the lens of that category instead

        // Find or create tags
        for tagName in response.tags {
            let lowercasedName = tagName.lowercased()
            let tagDescriptor = FetchDescriptor<Tag>(
                predicate: #Predicate<Tag> { $0.name == lowercasedName }
            )

            if let existingTag = try? context.fetch(tagDescriptor).first {
                if !item.tags.contains(where: { $0.id == existingTag.id }) {
                    item.tags.append(existingTag)
                    existingTag.incrementUsage()
                }
            } else {
                let newTag = Tag(name: lowercasedName, isAutoGenerated: true)
                context.insert(newTag)
                item.tags.append(newTag)
            }
        }

        // Apply other fields
        item.keyInsights = response.keyInsights
        item.contentSubtype = response.contentSubtype
        item.aiConfidence = response.confidence

        // Apply AI-generated title if provided
        if let suggestedTitle = response.suggestedTitle, !suggestedTitle.isEmpty {
            item.aiGeneratedTitle = suggestedTitle
        }

        // Apply extracted fields if provided
        if let extractedFields = response.extractedFields, !extractedFields.isEmpty {
            item.extractedFields = extractedFields
        }
    }

    /// Check if item has enough content to analyze
    private func hasEnoughContent(_ item: BookmarkItem) -> Bool {
        let titleLength = item.title.count
        let textLength = (item.rawText ?? "").count + (item.webContent?.extractedText ?? "").count

        return titleLength + textLength >= minContentLength
    }
}
