import Foundation
import SwiftData

@Model
final class Tag {
    @Attribute(.unique) var id: UUID
    var name: String
    var usageCount: Int
    var isAutoGenerated: Bool
    var createdAt: Date

    @Relationship(deleteRule: .nullify, inverse: \BookmarkItem.tags)
    var items: [BookmarkItem] = []

    init(
        id: UUID = UUID(),
        name: String,
        isAutoGenerated: Bool = true
    ) {
        self.id = id
        self.name = name
        self.usageCount = 0
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = Date()
    }

    func incrementUsage() {
        usageCount += 1
    }
}
